pull_request_rules:
  - name: automatic merge on review
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      comment:
        message: Thanks For Contributing to this project 🔥
      merge:
        method: squash
  - name: auto labeling for hacktoberfest
    conditions:
      - status-success=netlify/animoji/deploy-preview
    actions:
      label:
        add:
          - hacktoberfest
          - need-review
      comment:
        message: Thanks for Opening pull request ✨
      request_reviews:
        users:
          - 2pai
          - YogaSakti
