export default [{
    animeEmoji: '💪👊👨‍🦳😻',
    animeName: '3-gatsu no Lion',
    animeYear: 2016,
    animeLink: 'https://myanimelist.net/anime/31646/3-gatsu_no_Lion',
  },
  {
    animeEmoji: '🗼 🔮 💥 🏍️',
    animeName: 'Akira',
    animeYear: 1988,
    animeLink: 'https://myanimelist.net/anime/47/Akira',
  },
  {
    animeEmoji: ' 🎤 🎸 😥',
    animeName: 'Angel Beats',
    animeYear: 2010,
    animeLink: 'https://myanimelist.net/anime/6547/Angel_Beats',
  },
  {
    animeEmoji: '🤧 🧒🏻 🌼 😥',
    animeName: 'Ano Hi Mita Hana no Namae wo Bokutachi wa Mada Shiranai',
    animeYear: 2011,
    animeLink: 'https://myanimelist.net/anime/9989/Ano_Hi_Mita_Hana_no_Namae_wo_Bokutachi_wa_Mada_Shiranai',
  },
  {
    animeEmoji: '👻 😖 🔪 🌂',
    animeName: 'Another',
    animeYear: 2012,
    animeLink: 'https://myanimelist.net/anime/11111/Another',
  },
  {
    animeEmoji: ' 🐙🔫🏫',
    animeName: 'Assassination Classroom',
    animeYear: 2015,
    animeLink: 'https://myanimelist.net/anime/24833/Ansatsu_Kyoushitsu',
  },
  {
    animeEmoji: '🚴️👦️👓️',
    animeName: 'Ba La La Xiao Mo Xian Zhi: Qiji Wubu',
    animeYear: 2013,
    animeLink: 'https://myanimelist.net/anime/31965/Ba_La_La_Xiao_Mo_Xian_Zhi__Qiji_Wubu',
  },
  {
    animeEmoji: '🧛‍♂️🦀🐌🐒🐍🐈',
    animeName: 'Bakemonogatari',
    animeYear: 2010,
    animeLink: 'https://myanimelist.net/anime/5081/Bakemonogatari',
  },
  {
    animeEmoji: '🍌😻🐱',
    animeName: 'Bananya: Fushigi na Nakama-tachi',
    animeYear: 2019,
    animeLink: 'https://myanimelist.net/anime/40228/Bananya__Fushigi_na_Nakama-tachi',
  },
  {
    animeEmoji: '🧑🏻👩🏼⏳🎆🎇',
    animeName: 'Black Clover',
    animeYear: 2017,
    animeLink: ' https://myanimelist.net/anime/34572/Black_Clover',
  },
  {
    animeEmoji: '⚫️😺⚔️ 👘',
    animeName: 'Black Cat',
    animeYear: 2006,
    animeLink: 'https://myanimelist.net/anime/68/Black_Cat/'
  },
  {
    animeEmoji: '⚔️💀🧡',
    animeName: 'Bleach',
    animeYear: 2004,
    animeLink: 'https://myanimelist.net/anime/269/Bleach'
  },
  {
    animeEmoji: '🏆 🤼‍ ♂ 🙌🏼 🙏 ♀',
    animeName: 'Boku no Hero Academia',
    animeYear: 2016,
    animeLink: 'https://myanimelist.net/anime/31964/Boku_no_Hero_Academia',
  },
  {
    animeEmoji: '🤟🙏🤙🏃‍♀️😺',
    animeName: 'Boruto',
    animeYear: 2017,
    animeLink: 'https://myanimelist.net/anime/34566/Boruto__Naruto_Next_Generations',
  },
  {
    animeEmoji: '👊🏼 💪🏻 👦🏻 🕵️',
    animeName: 'Bungou Stray Dogs 3rd Season (2019)',
    animeYear: 2019,
    animeLink: 'https://myanimelist.net/anime/38003/Bungou_Stray_Dogs_3rd_Season',
  },
  {
    animeEmoji: '⚽️ 🏆 🤝 🏅 🏟',
    animeName: 'Captain Tsubasa',
    animeYear: 2018,
    animeLink: 'https://myanimelist.net/anime/36934/Captain_Tsubasa_2018',
  },
  {
    animeEmoji: '👧💕👦🐱🃏',
    animeName: 'Cardcaptor Sakura',
    animeYear: 2000,
    animeLink: 'https://myanimelist.net/anime/232/Cardcaptor_Sakura',
  },
  {
    animeEmoji: '🔫⚔👦🔍🔐💣',
    animeName: 'City Hunter',
    animeYear: 1987,
    animeLink: 'https://myanimelist.net/anime/1470/City_Hunter',
  },
  {
    animeEmoji: '👁😈🍕🍕🍕',
    animeName: 'Code Geass: Lelouch of the Rebellion',
    animeYear: 2006,
    animeLink: 'https://myanimelist.net/anime/1575/Code_Geass__Hangyaku_no_Lelouch',
  },
  {
    animeEmoji: '👠🕶🚬💰🦊',
    animeName: 'Cowboy Bebop',
    animeYear: 1998,
    animeLink: 'https://myanimelist.net/anime/1/Cowboy_Bebop',
  },
  {
    animeEmoji: '👦 👩 ⚔️  ⚡️🙍',
    animeName: 'Crayon Shin-chan',
    animeYear: 1990,
    animeLink: 'https://myanimelist.net/manga/2435/Crayon_Shin-chan?q=chinchan',
  },
  {
    animeEmoji: "🤴🎾🧢",
    animeName: "The Prince of Tennis",
    animeYear: 2001,
    animeLink: "https://myanimelist.net/anime/22/Tennis_no_Ouji-sama?q=Prince%20of%20Tennis"
  },
  {
    animeEmoji: '🐼💀🕵🏻⚖️',
    animeName: 'Danganronpa: The Animation',
    animeYear: 2013,
    animeLink: 'https://myanimelist.net/anime/16592/Danganronpa__Kibou_no_Gakuen_to_Zetsubou_no_Koukousei_The_Animation',
  },
  {
    animeEmoji: '😱 😖 ⚖️ 🔪',
    animeName: 'Death Parade',
    animeYear: 2015,
    animeLink: 'https://myanimelist.net/anime/28223/Death_Parade',
  },
  {
    animeEmoji: '👦👹✍️🤕💀',
    animeName: 'Death Note',
    animeYear: 2007,
    animeLink: 'https://myanimelist.net/anime/1535/Death_Note',
  },
  {
    animeEmoji: ' ⚔️ 🙍🏻‍♂️🙍🏼‍♀️ 🙏🏼',
    animeName: 'Demon Slayer: Kimetsu no Yaiba',
    animeYear: 2019,
    animeLink: 'https://myanimelist.net/anime/38000/Kimetsu_no_Yaiba',
  },
  {
    animeEmoji: '😎🕵️👓',
    animeName: 'Detective Conan',
    animeYear: 1996,
    animeLink: 'https://myanimelist.net/anime/235/Detective_Conan',
  },
  {
    animeEmoji: '👼🏻👼👩👩',
    animeName: 'D.N.Angel',
    animeYear: 2003,
    animeLink: 'https://myanimelist.net/anime/61/DNAngel',
  },
  {
    animeEmoji: '🐱🤓👩🏻‍🦰',
    animeName: 'Doraemon',
    animeYear: 1973,
    animeLink: 'https://myanimelist.net/anime/501/Doraemon',
  },
  {
    animeEmoji: '🤵🏼👊🏼👱🏼🤟🏼',
    animeName: 'Dr. Stone',
    animeYear: 2017,
    animeLink: 'https://myanimelist.net/anime/38691/Dr_Stone',
  },
  {
    animeEmoji: '🐲 👊 🚀',
    animeName: 'Dragon Ball GT',
    animeYear: 1996,
    animeLink: 'https://myanimelist.net/anime/225/Dragon_Ball_GT',
  },
  {
    animeEmoji: '🐲 👊 🌌',
    animeName: 'Dragon Ball Super',
    animeYear: 2015,
    animeLink: 'https://myanimelist.net/anime/30694/Dragon_Ball_Super',
  },
  {
    animeEmoji: '🐲 👊 🥋',
    animeName: 'Dragon Ball Z',
    animeYear: 1989,
    animeLink: 'https://myanimelist.net/anime/813/Dragon_Ball_Z',
  },
  {
    animeEmoji: '🧝🤥🔪🧠',
    animeName: 'Elfen Lied',
    animeYear: 2004,
    animeLink: 'https://myanimelist.net/anime/226/Elfen_Lied',
  },
  {
    animeEmoji: '🏃🏉💪👊',
    animeName: 'Eyeshield 21',
    animeYear: 2005,
    animeLink: 'https://myanimelist.net/anime/15/Eyeshield_21',
  },
  {
    animeEmoji: '⚔️ 🏆 ♟️ 🏹',
    animeName: 'Fate/stay night: Unlimited Blade Works',
    animeYear: 2014,
    animeLink: 'https://myanimelist.net/anime/22297/Fate_stay_night__Unlimited_Blade_Works',
  },
  {
    animeEmoji: '🏊🏊🏊🏊🏊',
    animeName: 'Free!',
    animeYear: 2013,
    animeLink: 'https://myanimelist.net/anime/18507/Free',
  },
  {
    animeEmoji: '👻↪️🐚🤖',
    animeName: 'Ghost in the Shell',
    animeYear: 1995,
    animeLink: 'https://myanimelist.net/anime/43/Koukaku_Kidoutai',
  },
  {
    animeEmoji: '👩🐉👩‍💼',
    animeName: 'Kobayashi-san Chi no Maid Dragon',
    animeYear: 2017,
    animeLink: 'https://myanimelist.net/anime/33206/Kobayashi-san_Chi_no_Maid_Dragon',
  },
  {
    animeEmoji: ' 🏀 🏆 ⛹🏻‍♂️',
    animeName: "Kuroko's Basketball",
    animeYear: 2012,
    animeLink: 'https://myanimelist.net/anime/11771/Kuroko_no_Basket',
  },
  {
    animeEmoji: '⚽️ 🏆 🤼‍♂️ 🙌🏼 🙏🏼',
    animeName: 'Giant Killing',
    animeYear: 2010,
    animeLink: 'https://myanimelist.net/anime/7661/Giant_Killing',
  },
  {
    animeEmoji: '👨🏻‍🌾  👩🏻‍🌾 🐎 🐄 🍕',
    animeName: 'Gin No Saji (Silver Spoon)',
    animeYear: 2013,
    animeLink: 'https://myanimelist.net/anime/16918/Gin_no_Saji',
  },
  {
    animeEmoji: '😆😆🤣✊👊',
    animeName: 'Gintama',
    animeYear: 2006,
    animeLink: 'https://myanimelist.net/anime/918/Gintama',
  },
  {
    animeEmoji: '👩‍🦳 👩 👨 ⚔️ 👺 ',
    animeName: 'Goblin Slayer',
    animeYear: 2018,
    animeLink: 'https://myanimelist.net/anime/37349/Goblin_Slayer',
  },
  {
    animeEmoji: '😜 🤝 🙏 🏆',
    animeName: 'Golden Boy',
    animeYear: 1995,
    animeLink: 'https://myanimelist.net/anime/268/Golden_Boy',
  },
  {
    animeEmoji: '🏆🏀🏀',
    animeName: 'Haikyuu',
    animeYear: 2014,
    animeLink: 'https://myanimelist.net/anime/20583/Haikyuu?q=haiky',
  },
  {
    animeEmoji: '⚔️👹🙍🏻‍♂️ 🙏🏼',
    animeName: 'Hellsing',
    animeYear: 2002,
    animeLink: 'https://myanimelist.net/anime/270/Hellsing',
  },
  {
    animeEmoji: ' 🙋🏻🎺🙋🏻🎷🎼',
    animeName: 'Hibike! Euphonium',
    animeYear: 2015,
    animeLink: 'https://myanimelist.net/anime/27989/Hibike_Euphonium',
  },
  {
    animeEmoji: '👨🏻‍🎓🐶👩🏻‍🎓',
    animeName: 'His and Her Circumstances (Kare Kano)',
    animeYear: 1998,
    animeLink: 'https://myanimelist.net/anime/145/Kareshi_Kanojo_no_Jijou',
  },
  {
    animeEmoji: '🤝 🏹  🏔  ⚔ 🙏🏼',
    animeName: 'Hunter x Hunter',
    animeYear: 2011,
    animeLink: 'https://myanimelist.net/anime/11061/Hunter_x_Hunter_2011',
  },
  {
    animeEmoji: ' 🎤 🎸 😥',
    animeName: 'Hyouka',
    animeYear: 2012,
    animeLink: 'https://myanimelist.net/anime/12189/Hyouka',
  },
  {
    animeEmoji: '👽 🎹 ⛑️ 🤖 🤖',
    animeName: 'Interstella5555: The 5tory of The 5ecret 5tar 5ystem',
    animeYear: 2003,
    animeLink: 'https://myanimelist.net/anime/731/Interstella5555__The_5tory_of_The_5ecret_5tar_5ystem',
  },
  {
    animeEmoji: '👱🏻🚙🏎🛣⛰',
    animeName: 'Initial D First Stage',
    animeYear: 1998,
    animeLink: 'https://myanimelist.net/anime/185/Initial_D_First_Stage',
  },
  {
    animeEmoji: '🧛🏻‍ 🏹 🔮',
    animeName: 'Inuyasha',
    animeYear: 2000,
    animeLink: 'https://myanimelist.net/anime/249/InuYasha',
  },
  {
    animeEmoji: '👊🏻💪🏻🤴🏻⚔️😎',
    animeName: 'K',
    animeYear: 2012,
    animeLink: 'https://myanimelist.net/anime/14467/K'
  },
  {
    animeEmoji: '🎸🎹🥁🏫❤️',
    animeName: 'K-on!',
    animeYear: 2009,
    animeLink: 'https://myanimelist.net/anime/5680/K-On'
  },
  {
    animeEmoji: '💑👫❤️🍰',
    animeName: 'Kaichou wa Maid-sama!',
    animeYear: 2010,
    animeLink: 'https://myanimelist.net/anime/7054/Kaichou_wa_Maid-sama',
  },
  {
    animeEmoji: '👊🏼 💪🏻 🌟 😤',
    animeName: 'Kenja no Mago',
    animeYear: 2019,
    animeLink: 'https://myanimelist.net/anime/36407/Kenja_no_Mago',
  },
  {
    animeEmoji: '✂️ 👚 🧵 👽',
    animeName: 'Kill la Kill',
    animeYear: 2013,
    animeLink: 'https://myanimelist.net/anime/18679/Kill_la_Kill',
  },
  {
    animeEmoji: '🤵🏼👊🏼👱🏼',
    animeName: 'Kimetsu no Yaiba',
    animeYear: 2019,
    animeLink: 'https://myanimelist.net/anime/38000/Kimetsu_no_Yaiba',
  },
  {
    animeEmoji: '😆 👩🏻‍ 👦🏻 👭',
    animeName: 'Kimi no Nawa',
    animeYear: 2016,
    animeLink: 'https://myanimelist.net/anime/32281/Kimi_no_Na_wa',
  },
  {
    animeEmoji: '🚫️ 🔈 👦🏻 👩🏼',
    animeName: 'Koe no Katachi (A Silent Voice)',
    animeYear: 2016,
    animeLink: 'https://myanimelist.net/anime/28851/Koe_no_Katachi',
  },
  {
    animeEmoji: '👨‍🎓 ❤️ 👩‍🏫 ☔️ 👠',
    animeName: 'Kotonoha no Niwa',
    animeYear: 2013,
    animeLink: 'https://myanimelist.net/anime/16782/Kotonoha_no_Niwa',
  },
  {
    animeEmoji: ' 🏀 🏆 ⛹🏻‍♂️',
    animeName: "Kuroko's Basketball",
    animeYear: 2012,
    animeLink: 'https://myanimelist.net/anime/11771/Kuroko_no_Basket',
  },
  {
    animeEmoji: '😤 💪🏽 🤵🏻 🔪',
    animeName: "Kuroshitsuji Movie: Book of the Atlantic (2017)",
    animeYear: 2017,
    animeLink: 'https://myanimelist.net/anime/31812/Kuroshitsuji_Movie__Book_of_the_Atlantic',
  },
  {
    animeEmoji: '💫 👼🏼 🌟 👊🏼',
    animeName: 'Magi: The Kingdom of Magic',
    animeYear: '2013-2014',
    animeLink: 'https://myanimelist.net/anime/18115/Magi__The_Kingdom_of_Magic',
  },
  {
    animeEmoji: '📕📱🔪',
    animeName: 'Mirai Nikki',
    animeYear: 2011,
    animeLink: 'https://myanimelist.net/anime/10620/Mirai_Nikki',
  },
  {
    animeEmoji: '⚔ 👹 🐷 ❤ 🧚‍',
    animeName: 'Nanatsu no Taizai',
    animeYear: 2014,
    animeLink: 'https://myanimelist.net/anime/23755/Nanatsu_no_Taizai',
  },
  {
    animeEmoji: '🤟🙏🤙🏃‍♀️😺',
    animeName: 'Naruto: Shippuuden',
    animeYear: 2007,
    animeLink: 'https://myanimelist.net/anime/1735/Naruto__Shippuuden',
  },
  {
    animeEmoji: '🧑😺👹👺👻',
    animeName: 'Natsume Yuujinchou',
    animeYear: 2008,
    animeLink: 'https://myanimelist.net/anime/4081/Natsume_Yuujinchou',
  },

  {
    animeEmoji: '🤙🏃‍♀️😺',
    animeName: 'Nendo no Tatakai',
    animeYear: 2019,
    animeLink: 'https://myanimelist.net/anime/40282/Nendo_no_Tatakai_2019',
  },
  {
    animeEmoji: ' 🚫🎮🚫🌱',
    animeName: 'No Game No life',
    animeYear: 2014,
    animeLink: 'https://myanimelist.net/anime/19815/No_Game_No_Life',
  },
  {
    animeEmoji: '🚢 🐒 ☠ 🌊 👑',
    animeName: 'One Piece',
    animeYear: 1999,
    animeLink: 'https://myanimelist.net/anime/21/One_Piece',
  },
  {
    animeEmoji: '💪👨‍ 👊👊',
    animeName: 'One Punch Man',
    animeYear: 2015,
    animeLink: 'https://myanimelist.net/anime/30276/One_Punch_Man',
  },
  {
    animeEmoji: '💀 🏰 🐹',
    animeName: 'Overlord',
    animeYear: 2015,
    animeLink: 'https://myanimelist.net/anime/29803/Overlord',
  },
  {
    animeEmoji: '🐧🥁🍎',
    animeName: 'Penguindrum',
    animeYear: 2011,
    animeLink: 'https://myanimelist.net/anime/10721/Mawaru_Penguindrum',
  },
  {
    animeEmoji: '🤖🙎‍♀️😭🙍🏻‍♂️',
    animeName: 'Plastic Memories',
    animeYear: 2015,
    animeLink: 'https://myanimelist.net/anime/27775/Plastic_Memories',
  },
  {
    animeEmoji: '👣😸👘👩‍👩‍👦‍👦🙇',
    animeName: 'Pokemon XY',
    animeYear: 2013,
    animeLink: 'https://myanimelist.net/anime/19291/Pokemon_XY',
  },
  {
    animeEmoji: '🐱🔫🧙‍♀️⏱',
    animeName: 'Puella Magi Madoka Magica',
    animeYear: 2011,
    animeLink: 'https://myanimelist.net/anime/9756/Mahou_Shoujo_Madoka%E2%98%85Magica',
  },
  {
    animeEmoji: '👩‍👩‍👧👩🏼‍🏫📚📖🥊',
    animeName: 'R.O.D.: The TV',
    animeYear: 2003,
    animeLink: 'https://myanimelist.net/anime/209/ROD__The_TV',
  },
  {
    animeEmoji: '🧑🏻👩🏼🎨👩🏼🐈',
    animeName: 'Sakurasou no Pet na Kanojo',
    animeYear: 2012,
    animeLink: 'https://myanimelist.net/anime/13759/Sakurasou_no_Pet_na_Kanojo',
  },
  {
    animeEmoji: '👩‍💻 📧 👻 🕴️ 🌐',
    animeName: "Serial Experiments Lain",
    animeYear: 1998,
    animeLink: 'https://myanimelist.net/anime/339/Serial_Experiments_Lain',
  },
  {
    animeEmoji: ' 👦🏻👩🏼🎻🎹😭',
    animeName: 'Shigatsu wa Kimi no Uso',
    animeYear: 2014,
    animeLink: 'https://myanimelist.net/anime/23273/Shigatsu_wa_Kimi_no_Uso',
  },
  {
    animeEmoji: '⚔️👱🏻🐎👩🏻',
    animeName: 'Shingeki no bahamut',
    animeYear: 2014,
    animeLink: 'https://myanimelist.net/anime/21843/Shingeki_no_Bahamut__Genesis',
  },
  {
    animeEmoji: '👊 🥘 🌎',
    animeName: 'Shokugeki no Souma',
    animeYear: 2015,
    animeLink: 'https://myanimelist.net/anime/28171/Shokugeki_no_Souma',
  },
  {
    animeEmoji: '🌹⚔️🌹🏰',
    animeName: 'Shoujo Kakumei Utena',
    animeYear: 1997,
    animeLink: 'https://myanimelist.net/anime/440/Shoujo_Kakumei_Utena',
  },
  {
    animeEmoji: '👨‍🚀 🐱 🤖 📠 👽',
    animeName: 'Space☆Dandy',
    animeYear: 2014,
    animeLink: 'https://myanimelist.net/anime/20057/Space☆Dandy',
  },
  {
    animeEmoji: '🤨 🧐 👨🏽‍💻 👨🏻‍🔬 👩🏻‍🔬',
    animeName: 'Steins;Gate',
    animeYear: 2011,
    animeLink: 'https://myanimelist.net/anime/9253/Steins_Gate',
  },
  {
    animeEmoji: ' ⚔️⚡️🙍🏻‍♂️🙍🏼‍♀️🧚🏻‍♂️',
    animeName: 'Sword Art Online',
    animeYear: 2012,
    animeLink: 'https://myanimelist.net/anime/11757/Sword_Art_Online',
  },
  {
    animeEmoji: '🗼🏢💣💥',
    animeName: 'Terror in Resonance',
    animeYear: 2014,
    animeLink: 'https://myanimelist.net/anime/23283/Zankyou_no_Terror',
  },
  {
    animeEmoji: '👁🐰🐛☕🎭',
    animeName: 'Tokyo Ghoul',
    animeYear: 2014,
    animeLink: 'https://myanimelist.net/anime/22319/Tokyo_Ghoul',
  },
  {
    animeEmoji: '🧑🏻👩🏼⏳🎆🎇',
    animeName: 'Uchiage Hanabi, Shita kara Miru ka Yoko kara Miru ka',
    animeYear: 2017,
    animeLink: 'https://myanimelist.net/anime/34498/Uchiage_Hanabi_Shita_kara_Miru_ka_Yoko_kara_Miru_ka',
  },
  {
    animeEmoji: '🔫🧛‍🧛‍🧛‍',
    animeName: 'Vampire Knight',
    animeYear: 2008,
    animeLink: 'https://myanimelist.net/anime/3457/Vampire_Knight',
  },
  {
    animeEmoji: '😢 😭 ✍️ 💌',
    animeName: 'Violet Evergarden',
    animeYear: 2018,
    animeLink: 'https://myanimelist.net/anime/33352/Violet_Evergarden',
  },
  {
    animeEmoji: '📚👩‍💼💕🎮👨🏻‍💼',
    animeName: 'Wotaku ni Koi wa Muzukashii (Wotakoi)',
    animeYear: 2018,
    animeLink: 'https://myanimelist.net/anime/35968/Wotaku_ni_Koi_wa_Muzukashii',
  },
  {
    animeEmoji: '🤔 👊🏻 📖 🏴‍☠️',
    animeName: 'Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e (Classroom of the Elite)',
    animeYear: 2017,
    animeLink: 'https://myanimelist.net/anime/35507/Youkoso_Jitsuryoku_Shijou_Shugi_no_Kyoushitsu_e',
  },
  {
    animeEmoji: '🚴️👦️👓️🏆️',
    animeName: 'Yowamushi Pedal',
    animeYear: 2013,
    animeLink: 'https://myanimelist.net/anime/18179/Yowamushi_Pedal',
  },
  {
    animeEmoji: '🤵🏼👊🏼👱🏼',
    animeName: 'Kimetsu_no_Yaiba',
    animeYear: 2019,
    animeLink: 'https://myanimelist.net/anime/38000/Kimetsu_no_Yaiba',
  },
  {
    animeEmoji: '🤵🏼👊🏼🏻👩🏼🎨',
    animeName: 'Made in Abyss',
    animeYear: 2017,
    animeLink: 'https://myanimelist.net/anime/34599/Made_in_Abyss',
  },
  {
    animeEmoji: '😭👼😇🤖',
    animeName: 'Neon Genesis Evangelion',
    animeYear: 1995,
    animeLink: 'https://myanimelist.net/anime/30/Neon_Genesis_Evangelion',
  },
  {
    animeEmoji: '😭🚗☃',
    animeName: 'Boku dake ga Inai Machi',
    animeYear: 2016,
    animeLink: 'https://myanimelist.net/anime/31043/Boku_dake_ga_Inai_Machi',
  },
  {
    animeEmoji: '👊🏻 👦🏻 🤼‍',
    animeName: 'Vinland Saga',
    animeYear: 2019,
    animeLink: 'https://myanimelist.net/anime/37521/Vinland_Saga',
  },
  {
    animeEmoji: '💥👺🏯👊⚔️🎎💕',
    animeName: 'Rurouni Kenshin: Meiji Kenkaku Romantan',
    animeYear: 1996,
    animeLink: 'https://myanimelist.net/anime/45/Rurouni_Kenshin__Meiji_Kenkaku_Romantan',
  },
  {
    animeEmoji: '⚔️👦🏻👩🏼👦🏻🥟',
    animeName: 'Samurai Champloo',
    animeYear: 2004,
    animeLink: 'https://myanimelist.net/anime/205/Samurai_Champloo',
  },
  {
    animeEmoji: '🧚🎢🎩',
    animeName: 'Amagi Brilliant Park',
    animeYear: 2014,
    animeLink: 'https://myanimelist.net/anime/22147/Amagi_Brilliant_Park',
  },
  {
    animeEmoji: '🍜🦊🍂👑👍🏻',
    animeName: 'Naruto',
    animeYear: 2002,
    animeLink: 'https://myanimelist.net/anime/20/Naruto',
  },
  {
    animeEmoji: '❤🃏👑🎮',
    animeName: 'Yu-Gi-Oh!',
    animeYear: 1998,
    animeLink: 'https://myanimelist.net/anime/550/Yu☆Gi☆Oh',
  },
  {
    animeEmoji: '👨‍👧🏝️🗾㊗️',
    animeName: 'Barakamon',
    animeYear: 2014,
    animeLink: 'https://myanimelist.net/anime/22789/Barakamon?q=Barakamon',
  },
  {
    animeEmoji: '🔭🌙🚀',
    animeName: 'Uchuu Kyoudai',
    animeYear: 2012,
    animeLink: 'https://myanimelist.net/anime/12431/Uchuu_Kyoudai',
  },
  {
    animeEmoji: '🔫🏅😂',
    animeName: 'Sabage-bu!',
    animeYear: 2014,
    animeLink: 'https://myanimelist.net/anime/20709/Sabage-bu',
  },
  {
    animeEmoji: '👨‍👧⚔️👺',
    animeName: 'Date A Live',
    animeYear: 2013,
    animeLink: 'https://myanimelist.net/anime/15583/Date_A_Live',
  },
  {
    animeEmoji: '😆👟🕊',
    animeName: 'Ao no Kanata no Four Rhythm',
    animeYear: '2016',
    animeLink: 'https://myanimelist.net/anime/28391/Ao_no_Kanata_no_Four_Rhythm'
  },
  {
    animeEmoji: '🕴🙏🤯🤰',
    animeName: 'Mugen no Juunin: Immortal',
    animeYear: 2019,
    animeLink: 'https://myanimelist.net/anime/39806/Mugen_no_Juunin__Immortal'
  },
  {
    animeEmoji: '⚔️👩🏻✂️🙎🏼',
    animeName: 'Akame ga kill',
    animeYear: 2014,
    animeLink: 'https://myanimelist.net/anime/22199/Akame_ga_Kill'
  },
  {
    animeEmoji: '🙎🏼👑👍🏻🦊👺',
    animeName: 'Slam Dunk',
    animeYear: 1993,
    animeLink: 'https://myanimelist.net/anime/170/Slam_Dunk'
  },
  {
    animeEmoji:'🍎👩🏻👱🏻‍🧑🏻',
    animeName:'Fruit Basket',
    animeYear:2001,
    animeLink:'https://myanimelist.net/anime/120/Fruits_Basket'
  }
];
